[tool.black]
line-length = 79

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 79

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.settings"
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests",
]